apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-d8cs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-d8cs
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-d8cs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-d8cs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-d8cs
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-kora-tenant/dotnet-component/devfile-sample-dotnet60-basic-d8cs@sha256:9b7f60c9293f9d1472bf42aeb8d1c2abac945cf654ae43068d062a9febdf59eb
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
